import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        padding: 21,
        backgroundColor: "#fff",
    },
    titleContainer: {
        flexDirection: "column",
        justifyContent: "space-between",
        alignItems: "flex-start",
        marginBottom: 35,
    },
    title: {
        fontSize: 32,
        fontWeight: "bold",
        color: "#000000",
        marginBottom: 5,
    },
    subtitle: {
        fontSize: 21,
        fontWeight: "700",
        color: "#F29D38",
    },
    selectMonthContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        zIndex: 1000,
        gap: 10,
        marginBottom: 50,
    },
    selectMonthText: {
        fontSize: 18,
        fontWeight: "normal",
        color: "#000000",
    },
    selectMonthInput: {
        fontSize: 18,
        fontWeight: "normal",
        color: "#000000",
        borderWidth: 1,
        borderColor: "#CCCCCC",
        padding: 10,
        borderRadius: 8,
        height: 40,
    },
    availableDateContainer: {
        flexDirection: "column",
        justifyContent: "flex-start",   
        gap: 10,
        marginBottom: 21,
    },
    availableDateHeader: {
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
        marginLeft: 10,
        marginRight: 10,
        gap: 20,
    },
    headerCol: {
        width: '27%',
    },
    availableDateTextWrapper: {
        flexDirection: "column",
        justifyContent: "space-between",
        gap: 5,
    },
    availableDateHeaderText: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#000000",
        textTransform: "uppercase",
        // borderWidth: 1,
    },
    availableDateHeaderTextDay: {
        fontSize: 13,
        fontWeight: "bold",
        color: "#606060",
    },
    availableDateList: {
        borderColor: "#D9D9D9",
        borderWidth: 1,
        borderRadius: 8,
    },
    insideContainer: {
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
        gap: 19,
        paddingVertical: 18,
        paddingHorizontal: 13,
    },
    insideContainerActive: {
        flexDirection: "row",
        backgroundColor: "#F3F4F6",
        justifyContent: "flex-start",
        alignItems: "center",
        gap: 19,
        paddingVertical: 18,
        paddingHorizontal: 13,
    },
    insideText: {
        fontSize: 14,
        fontWeight: "bold",
        color: "#000000",
    },
    listExpandContainer: {
        flexDirection: "column",
        justifyContent: "space-between",
        alignItems: "flex-start",
        padding: 15,
    },
    listExpand: {
        flexDirection: "row",
        justifyContent: "space-between",
        // alignItems: "flex-start",
        gap: 10,
        backgroundColor: '#FFFFFF',
    },
    listExpandLeftSide: {
        flexDirection: "column",
        justifyContent: "space-between",
        gap: 5,
        width: '50%',
    },
    listExpandText: {
        fontSize: 15,
        color: "#000000",
        fontWeight: "bold",
        marginBottom: 8,
    },
    groupDate: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        // gap: 2,
        marginBottom: 8,
    },
    groupDateText: {
        fontSize: 11,
        fontWeight: "bold",
        color: "#375FA2",
        backgroundColor: "#EBF6FF",
        paddingVertical: 8,
        paddingHorizontal: 21,
        textAlign: "center",
        borderRadius: 8,
        width: '40%',
    },
    groupDateTextWrapper: {
        flexDirection: "column",
        justifyContent: "space-between",
        gap: 5,
    },
    groupDateTextDate: {
        fontSize: 12,
        fontWeight: "bold",
        color: "#000000",
    },
    groupDateTextDay: {
        fontSize: 10,
        fontWeight: "bold",
        color: "#606060",
    },
    listExpandRightSide: {
        flexDirection: "column",
        justifyContent: "space-between",
        gap: 5,
        width: '50%',
    },
    groupPrice: {
        flexDirection: "column",
        justifyContent: "space-between",
        alignItems: "center",
        gap: 5,
        marginBottom: 10,
    },
    groupPriceCaption: {
        fontSize: 12,
        fontWeight: "normal",
        color: "#3A5694",
    },
    groupPriceText: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#EF4444",
    },
    groupButtons: {
        flexDirection: "column",
        justifyContent: "space-between",
        alignItems: "center",
        gap: 5,
        marginBottom: 10,
    },
    buttonEasyQuote: {
        borderWidth: 1,
        borderColor: "#3A5694",
        borderRadius: 8,
        paddingVertical: 12,
        // paddingHorizontal: 21,
        width: '70%',
        marginBottom: 21,
    },
    easyQuoteText: {
        fontSize: 14,
        color: "#3A5694",
        textAlign: "center",
    },
    buttonBookNow: {
        backgroundColor: "#3A5694",
        borderRadius: 8,
        paddingVertical: 12,
        paddingHorizontal: 21,
        width: '70%',
    },
    bookNowText: {
        fontSize: 14,
        color: "#FFFFFF",
        textAlign: "center",
    },
    callUsText: {
        fontSize: 13,
        marginTop: 10,
        color: "#EF4444",
        fontWeight: "normal",
    }
});