import { StyleSheet } from "react-native";

const COLORS = {
  primary: "#FF8000",
  white: "#FFFFFF",
  black: "#000000",
  lightGray: "#F5F5F5",
  gray: "#8A8A8A",
  darkGray: "#333333",
  green: "#28a745",
  lightGreen: "#EAF7EC",
  red: "#dc3545",
  lightRed: "#FBEBEE",
  blue: "#007bff",
  lightBlue: "#E6F2FF",
  orange: "#fd7e14",
  lightOrange: "#FFF3E8",
};

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.lightGray,
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 10,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: "#EAEAEA",
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    color: COLORS.darkGray,
  },
  backButton: {
    padding: 6,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 16,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.darkGray,
    marginBottom: 16,
  },
  statusBadge: {
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 20,
  },
  statusText: {
    fontSize: 12,
    fontWeight: "bold",
  },
  statusBadgeCompleted: { backgroundColor: COLORS.lightGreen },
  statusTextCompleted: { color: COLORS.green },
  statusBadgeProcessed: { backgroundColor: COLORS.lightBlue },
  statusTextProcessed: { color: COLORS.blue },
  statusBadgeCancelled: { backgroundColor: COLORS.lightRed },
  statusTextCancelled: { color: COLORS.red },
  statusBadgePending: { backgroundColor: COLORS.lightOrange },
  statusTextPending: { color: COLORS.orange },

  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  infoLabel: {
    fontSize: 14,
    color: COLORS.gray,
  },
  infoValue: {
    fontSize: 14,
    color: COLORS.darkGray,
    fontWeight: "500",
    flex: 1,
    textAlign: "right",
  },
  serviceContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  serviceImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 12,
  },
  serviceTextContainer: {
    flex: 1,
  },
  serviceName: {
    fontSize: 15,
    fontWeight: "bold",
    color: COLORS.darkGray,
  },
  providerName: {
    fontSize: 13,
    color: COLORS.gray,
    marginTop: 4,
  },
  divider: {
    height: 1,
    backgroundColor: "#EAEAEA",
    marginVertical: 12,
  },
  totalLabel: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.darkGray,
  },
  totalValue: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.primary,
  },
  actionContainer: {
    flexDirection: "column",
    padding: 16,
    gap: 16,
  },
  primaryButton: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: COLORS.primary,
    padding: 14,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  primaryButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: "bold",
  },
  secondaryButton: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: COLORS.white,
    padding: 14,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.primary,
    gap: 8,
  },
  secondaryButtonText: {
    color: COLORS.primary,
    fontSize: 16,
    fontWeight: "bold",
  },
  cancelButton: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: COLORS.lightRed,
    padding: 14,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.red,
    gap: 8,
  },
  cancelButtonText: {
    color: COLORS.red,
    fontSize: 16,
    fontWeight: "bold",
  },
  disabledButton: {
    backgroundColor: "#BDBDBD",
    borderColor: "#BDBDBD",
  },
  disabledButtonText: {
    color: COLORS.darkGray,
  },
  reviewButton: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: COLORS.white,
    padding: 14,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.primary,
    gap: 8,
  },
  reviewButtonText: {
    color: COLORS.primary,
    fontSize: 16,
    fontWeight: "bold",
  },
});
