import { StyleSheet } from "react-native";
import { theme } from "@shared/constants/theme";

export default StyleSheet.create({
  container: {
    padding: 21,
    backgroundColor: theme.colors.white,
  },
  titleContainer: {
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 35,
  },
  title: {
    fontSize: theme.typography.fontSize.display,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.black,
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 21,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.primary,
  },
  selectMonthContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    zIndex: 1000,
    gap: 10,
    marginBottom: 50,
  },
  selectMonthText: {
    fontSize: theme.typography.fontSize.lg,
    fontWeight: theme.typography.fontWeight.regular,
    color: theme.colors.black,
  },
  selectMonthInput: {
    fontSize: theme.typography.fontSize.lg,
    fontWeight: theme.typography.fontWeight.regular,
    color: theme.colors.black,
    borderWidth: 1,
    borderColor: theme.colors.grey400,
    padding: 10,
    borderRadius: theme.radii.sm,
    height: 40,
  },
  availableDateContainer: {
    flexDirection: "column",
    justifyContent: "flex-start",
    gap: 10,
    marginBottom: 21,
  },
  availableDateHeader: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    marginLeft: 10,
    marginRight: 10,
    gap: theme.spacing.xl,
  },
  headerCol: {
    width: "27%",
  },
  availableDateTextWrapper: {
    flexDirection: "column",
    justifyContent: "space-between",
    gap: 5,
  },
  availableDateHeaderText: {
    fontSize: theme.typography.fontSize.md,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.black,
    textTransform: "uppercase",
  },
  availableDateHeaderTextDay: {
    fontSize: 13,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.grey600,
  },
  availableDateList: {
    borderColor: theme.colors.grey300,
    borderWidth: 1,
    borderRadius: theme.radii.sm,
  },
  insideContainer: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    gap: 19,
    paddingVertical: 18,
    paddingHorizontal: 13,
  },
  insideContainerActive: {
    flexDirection: "row",
    backgroundColor: theme.colors.grey100,
    justifyContent: "flex-start",
    alignItems: "center",
    gap: 19,
    paddingVertical: 18,
    paddingHorizontal: 13,
  },
  insideText: {
    fontSize: theme.typography.fontSize.sm,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.black,
  },
  listExpandContainer: {
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "flex-start",
    padding: 15,
  },
  listExpand: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 15,
    backgroundColor: theme.colors.white,
  },
  listExpandLeftSide: {
    flexDirection: "column",
    justifyContent: "space-between",
    gap: 5,
    width: "50%",
  },
  listExpandText: {
    fontSize: 15,
    color: theme.colors.black,
    fontWeight: theme.typography.fontWeight.bold,
    marginBottom: theme.spacing.sm,
  },
  groupDate: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 5,
    marginBottom: theme.spacing.sm,
  },
  groupDateText: {
    fontSize: 11,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.secondaryLight,
    backgroundColor: theme.colors.infoBackground,
    paddingVertical: theme.spacing.sm,
    paddingHorizontal: 21,
    textAlign: "center",
    borderRadius: theme.radii.sm,
    width: "40%",
  },
  groupDateTextWrapper: {
    flexDirection: "column",
    justifyContent: "space-between",
    gap: 5,
    flex: 1,
  },
  groupDateTextDate: {
    fontSize: 12,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.black,
  },
  groupDateTextDay: {
    fontSize: 10,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.grey600,
  },
  listExpandRightSide: {
    flexDirection: "column",
    justifyContent: "space-between",
    gap: 5,
    width: "50%",
  },
  groupPrice: {
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 5,
    marginBottom: 10,
  },
  groupPriceCaption: {
    fontSize: 12,
    fontWeight: theme.typography.fontWeight.regular,
    color: theme.colors.secondary,
  },
  groupPriceText: {
    fontSize: theme.typography.fontSize.md,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.error,
  },
  groupButtons: {
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 5,
    marginBottom: 10,
  },
  buttonEasyQuote: {
    borderWidth: 1,
    borderColor: theme.colors.secondary,
    borderRadius: theme.radii.sm,
    paddingVertical: theme.spacing.md,
    width: "70%",
    marginBottom: 21,
  },
  easyQuoteText: {
    fontSize: theme.typography.fontSize.sm,
    color: theme.colors.secondary,
    textAlign: "center",
  },
  buttonBookNow: {
    backgroundColor: theme.colors.secondary,
    borderRadius: theme.radii.sm,
    paddingVertical: theme.spacing.md,
    paddingHorizontal: 21,
    width: "70%",
  },
  bookNowText: {
    fontSize: theme.typography.fontSize.sm,
    color: theme.colors.white,
    textAlign: "center",
  },
  callUsText: {
    fontSize: 13,
    marginTop: 10,
    color: theme.colors.error,
    fontWeight: theme.typography.fontWeight.regular,
  },
  backButton: {
    backgroundColor: theme.colors.grey500,
    opacity: 0.8,
    padding: 5,
    borderRadius: 21,
    marginBottom: 5,
  },
});
